---
name: Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        illuminate-version:
          - 9
          - 10
        php-version:
          - 8.1
          - 8.2
        runs-on:
          - ubuntu-latest

    runs-on: ${{ matrix.runs-on }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Install Dependencies
        run: |
          composer require \
            --no-ansi \
            --no-interaction \
            --no-progress \
            --no-scripts \
            --prefer-dist \
            illuminate/support:^${{ matrix.illuminate-version }}

      - name: Lint Code
        run: vendor/bin/tlint

      - name: Laravel 10 Changes
        if: matrix.illuminate-version == 10
        run: |
          composer config minimum-stability stable --file composer.json
          vendor/bin/phpunit --migrate-configuration

      - name: Run Tests
        run: vendor/bin/phpunit --coverage-text
